### ISSUE TITLE
how do i add my minecraft server to lunar client server mappings (help)

### ISSUE THREAD

**Issue by Blake123kulaga** [LunarClient/BukkitImpl#19]
server IP; Clutchinc.myftp.org (Clutchinc)

**Comment by ThatKawaiiSam** [comment]
Howdy!

This is the repository for our Bukkit API plugin. You'll want to read the instructions over on the [ServerMappings](https://github.com/LunarClient/ServerMappings) repository and create a pull request with all of your server details.

If you need any additional help, please create a ticket over on our [Support portal](https://support.lunarclient.com).
