### ISSUE TITLE
Add fullbright as a mod you can disable

### ISSUE THREAD

**Issue by he3als** [LunarClient/BukkitImpl#5]
I know this is more of a performance enhancing thing, but for SMPs fullbright can be a real big and unfair advantage. You do not even need any source of light to go mining and see everything clearly in the night.

**Comment by DisabledMallis** [comment]
I am also going to second this, my server features a gamemode where this feature would ruin it.

**Comment by he3als** [comment]
Yeah, most of the players on my SMP use full bright while it is bannable. However, I can not control it.

**Comment by 10Meisterbaelle** [comment]
There’s no way to control whether someone is using fullbright, since you can literally get it in vanilla by changing the gamma

**Comment by DisabledMallis** [comment]
Ok, then let us control the gamma value? That'd be even better for what I'm trying to make.

**Comment by he3als** [comment]
> There’s no way to control whether someone is using fullbright, since you can literally get it in vanilla by changing the gamma
my players do not want to cheat as it is a quite small server. however, it is confusing switching between fullbright off and on constantly and they forget to turn it off a lot of the time. maybe lunar client could prevent invalid gamma values though?

**Comment by 10Meisterbaelle** [comment]
Unless you block every client that isn't Lunar Client (including Vanilla),
this won't really help

Am Mo., 24. Jan. 2022 um 15:04 Uhr schrieb Mike ***@***.***>:

**Comment by DisabledMallis** [comment]
Well my server is lunar only, because it requires some of these features that lunar has... being able to control the gamma is the last missing piece for me

**Comment by 10Meisterbaelle** [comment]
> Well my server is lunar only

but what stops people to join without it? do you have a plugin to stop non-lunar users?

> because it requires some of these features that lunar has...

No server REQUIRES lunar features

**Comment by LaserSlime** [comment]
I know I'm late, but the mod id for fullbright it "lighting".

**Comment by he3als** [comment]
Yeah, Lunar implemented has implemented this now.

Anyways, I think that fullbright should be allowed now anyways lol

**Comment by LaserSlime** [comment]
Same, it's kind of a shader at the end of the day.
